// <auto-generated />
using System;
using Capa.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capa.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capa.Shared.Entities.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NroCi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResumenPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("NroCi")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Capa.Shared.Entities.DocenteLineaInvestigacion", b =>
                {
                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("LineaInvestigacionId")
                        .HasColumnType("int");

                    b.HasKey("DocenteId", "LineaInvestigacionId");

                    b.HasIndex("LineaInvestigacionId");

                    b.ToTable("DocenteLineasInvestigacion");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NroCi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("NroCi")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Capa.Shared.Entities.HistorialTutoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.ToTable("HistorialTutorias");
                });

            modelBuilder.Entity("Capa.Shared.Entities.LineaInvestigacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LineasInvestigacion");
                });

            modelBuilder.Entity("Capa.Shared.Entities.ProyectoGrado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Gestion")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("LineaInvestigacionId")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("EstudianteId")
                        .IsUnique();

                    b.HasIndex("LineaInvestigacionId");

                    b.ToTable("ProyectoGrados");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Docente", b =>
                {
                    b.HasOne("Capa.Shared.Entities.Carrera", "Carrera")
                        .WithMany("Docentes")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Capa.Shared.Entities.DocenteLineaInvestigacion", b =>
                {
                    b.HasOne("Capa.Shared.Entities.Docente", "Docente")
                        .WithMany("LineasInvestigacion")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capa.Shared.Entities.LineaInvestigacion", "LineaInvestigacion")
                        .WithMany("Docentes")
                        .HasForeignKey("LineaInvestigacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("LineaInvestigacion");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Estudiante", b =>
                {
                    b.HasOne("Capa.Shared.Entities.Carrera", "Carrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Capa.Shared.Entities.HistorialTutoria", b =>
                {
                    b.HasOne("Capa.Shared.Entities.Docente", "Docente")
                        .WithMany("HistorialTutorias")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Capa.Shared.Entities.ProyectoGrado", b =>
                {
                    b.HasOne("Capa.Shared.Entities.Docente", "Docente")
                        .WithMany("Proyectos")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capa.Shared.Entities.Estudiante", "Estudiante")
                        .WithOne("ProyectoGrado")
                        .HasForeignKey("Capa.Shared.Entities.ProyectoGrado", "EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capa.Shared.Entities.LineaInvestigacion", "LineaInvestigacion")
                        .WithMany("Proyectos")
                        .HasForeignKey("LineaInvestigacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Docente");

                    b.Navigation("Estudiante");

                    b.Navigation("LineaInvestigacion");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Carrera", b =>
                {
                    b.Navigation("Docentes");

                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Docente", b =>
                {
                    b.Navigation("HistorialTutorias");

                    b.Navigation("LineasInvestigacion");

                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Estudiante", b =>
                {
                    b.Navigation("ProyectoGrado");
                });

            modelBuilder.Entity("Capa.Shared.Entities.LineaInvestigacion", b =>
                {
                    b.Navigation("Docentes");

                    b.Navigation("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
